name: CI
on:
  push:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Use Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: lts/*
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1
        with:
          working-directory: examples
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Build demo
        run: yarn build
        working-directory: examples
      - name: Deploy demo
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: examples/dist
