name: CI
on:
  push:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: examples
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Build demo
        run: yarn build
        working-directory: examples
      - name: Deploy demo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: examples/dist
